### ISSUE TITLE
'Empty sequence' sentinel value wedges pool

### ISSUE THREAD

**Issue by moea** [benashford/redis-async#2]
I just noticed this in a REPL with 0.2.0-beta1 against local Redis 2.8.4.

The channel returned from `(client/hgetall p "nonexistent")` is never realized, nor are any channels returned from subsequent operations in the same pool.  I also tried `sinter` on two non-intersecting sets, and got the same result - I guess it's an issue with the handling of the Redis _empty_ value.

**Comment by benashford** [comment]
Thanks for bringing this to my attention, it does look as though empty results are causing confusion.  Let me have a look, I'll get to the bottom of it.

**Comment by benashford** [comment]
It was as you suspected, specifically this: https://github.com/benashford/jresp/commit/5f21813ab2897a899d86c36efb7b3edae1d1e7bf empty results were causing things to get stuck because it would never acknowledge the end of the array.

I've published this to Clojars a few other fixes as 0.2.0-beta2.

Thanks
